package com.example.cordemo.model.model;

public class Admin {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.id
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.username
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    private String username;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.password
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column admin.adminType
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    private Integer admintype;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.id
     *
     * @return the value of admin.id
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.id
     *
     * @param id the value for admin.id
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.username
     *
     * @return the value of admin.username
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public String getUsername() {
        return username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.username
     *
     * @param username the value for admin.username
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.password
     *
     * @return the value of admin.password
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.password
     *
     * @param password the value for admin.password
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column admin.adminType
     *
     * @return the value of admin.adminType
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public Integer getAdmintype() {
        return admintype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column admin.adminType
     *
     * @param admintype the value for admin.adminType
     *
     * @mbg.generated Tue Mar 04 00:32:10 CST 2025
     */
    public void setAdmintype(Integer admintype) {
        this.admintype = admintype;
    }
}